import { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { getProfile, updateProfile, changePassword, getReportData } from '../utils/api';
import './Profile.css';

export default function Profile() {
  const { user, login } = useAuth();
  const [profile, setProfile] = useState(null);
  const [editName, setEditName] = useState('');
  const [passwords, setPasswords] = useState({ currentPassword: '', newPassword: '', confirmPassword: '' });
  const [nameSuccess, setNameSuccess] = useState('');
  const [passSuccess, setPassSuccess] = useState('');
  const [passError, setPassError] = useState('');
  const [loading, setLoading] = useState(true);

  useEffect(() => { loadProfile(); }, []);

  const loadProfile = async () => {
    try {
      const res = await getProfile();
      setProfile(res.data);
      setEditName(res.data.user.name);
    } catch (err) { console.error(err); }
    finally { setLoading(false); }
  };

  const handleNameUpdate = async () => {
    if (!editName.trim()) return;
    try {
      const res = await updateProfile({ name: editName });
      login(localStorage.getItem('serenity_token'), { ...user, name: res.data.name });
      setNameSuccess('Name updated! ✅');
      setTimeout(() => setNameSuccess(''), 3000);
    } catch (err) { console.error(err); }
  };

  const handlePasswordChange = async () => {
    setPassError(''); setPassSuccess('');
    if (passwords.newPassword !== passwords.confirmPassword) { setPassError('Passwords do not match'); return; }
    if (passwords.newPassword.length < 6) { setPassError('New password must be at least 6 characters'); return; }
    try {
      await changePassword({ currentPassword: passwords.currentPassword, newPassword: passwords.newPassword });
      setPassSuccess('Password changed successfully! ✅');
      setPasswords({ currentPassword: '', newPassword: '', confirmPassword: '' });
      setTimeout(() => setPassSuccess(''), 3000);
    } catch (err) {
      setPassError(err.response?.data?.message || 'Failed to change password');
    }
  };

  const handleExportReport = async () => {
    try {
      const res = await getReportData();
      const data = res.data;
      // Generate a simple text/HTML report and download
      const html = `
<!DOCTYPE html>
<html><head><title>Serenity Wellness Report - ${data.user.name}</title>
<style>
  body{font-family:Arial,sans-serif;max-width:800px;margin:40px auto;padding:20px;color:#3D4852;line-height:1.6}
  h1{color:#7BC8A4;border-bottom:2px solid #E8F5EE;padding-bottom:10px}
  h2{color:#7BC8A4;margin-top:30px}
  .score-box{display:inline-block;padding:8px 20px;border-radius:8px;margin:4px;font-weight:bold}
  .green{background:#E8F5EE;color:#7BC8A4} .blue{background:#E6F0FA;color:#89B4E8} .lavender{background:#F0EBF5;color:#B8A9C9}
  table{width:100%;border-collapse:collapse;margin:10px 0} td,th{padding:8px 12px;border:1px solid #EDE9E3;text-align:left}
  th{background:#FAFAF7} .footer{margin-top:40px;color:#A8B5BF;font-size:0.85rem;text-align:center}
</style></head><body>
<h1>🌿 Serenity Wellness Report</h1>
<p><strong>Name:</strong> ${data.user.name} | <strong>Email:</strong> ${data.user.email}</p>
<p><strong>Member since:</strong> ${new Date(data.user.memberSince).toLocaleDateString()} | <strong>Generated:</strong> ${new Date(data.generatedAt).toLocaleString()}</p>

<h2>📊 Wellness Scores</h2>
<p>
  <span class="score-box green">Overall: ${data.wellness?.overallScore || 0}%</span>
  <span class="score-box green">Physical: ${data.wellness?.physicalScore || 0}%</span>
  <span class="score-box blue">Mental: ${data.wellness?.mentalScore || 0}%</span>
  <span class="score-box lavender">Emotional: ${data.wellness?.emotionalScore || 0}%</span>
</p>

<h2>📝 Recent Assessments</h2>
<table><tr><th>Date</th><th>Category</th><th>Score</th></tr>
${data.recentAssessments.map(a => `<tr><td>${new Date(a.completedAt).toLocaleDateString()}</td><td>${a.category}</td><td>${a.score}%</td></tr>`).join('')}
</table>

<h2>😊 Recent Mood Check-ins</h2>
<table><tr><th>Date</th><th>Mood</th><th>Energy</th><th>Stress</th><th>Sleep</th></tr>
${data.recentMoods.map(m => `<tr><td>${new Date(m.date).toLocaleDateString()}</td><td>${m.mood}/5</td><td>${m.energy}/5</td><td>${m.stress}/5</td><td>${m.sleep}/5</td></tr>`).join('')}
</table>

<h2>🎯 Goals</h2>
<table><tr><th>Goal</th><th>Category</th><th>Progress</th><th>Status</th></tr>
${data.goals.map(g => `<tr><td>${g.title}</td><td>${g.category}</td><td>${g.currentProgress}/${g.targetScore}</td><td>${g.status}</td></tr>`).join('')}
</table>

${data.wellness?.recommendations?.length > 0 ? `
<h2>💡 Recommendations</h2>
<ul>${data.wellness.recommendations.map(r => `<li><strong>${r.icon} ${r.title}:</strong> ${r.description}</li>`).join('')}</ul>
` : ''}

<div class="footer"><p>Generated by Serenity Wellness Platform 🌿</p></div>
</body></html>`;

      const blob = new Blob([html], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `Serenity_Report_${data.user.name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.html`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) { console.error(err); }
  };

  if (loading) return <div className="profile-page"><div className="container" style={{ textAlign: 'center', paddingTop: 80 }}><p style={{ color: 'var(--text-muted)' }}>Loading profile...</p></div></div>;

  const p = profile;
  const w = p?.wellness;
  const s = p?.stats;

  return (
    <div className="profile-page">
      <div className="container">
        {/* Hero */}
        <div className="profile-hero">
          <div className="profile-avatar">{p?.user?.name?.[0]?.toUpperCase()}</div>
          <h1>{p?.user?.name}</h1>
          <p>{p?.user?.email}</p>
          <span className="member-badge">🌿 Member for {s?.memberDays || 0} days</span>
        </div>

        {/* Stats */}
        <div className="profile-stats">
          <div className="ps-card"><div className="ps-val" style={{ color: 'var(--green)' }}>{w?.overallScore || 0}</div><div className="ps-label">Wellness Score</div></div>
          <div className="ps-card"><div className="ps-val" style={{ color: 'var(--blue)' }}>{s?.totalAssessments || 0}</div><div className="ps-label">Assessments</div></div>
          <div className="ps-card"><div className="ps-val" style={{ color: 'var(--peach)' }}>{s?.totalMoodEntries || 0}</div><div className="ps-label">Check-ins</div></div>
          <div className="ps-card"><div className="ps-val" style={{ color: 'var(--lavender)' }}>{s?.totalJournals || 0}</div><div className="ps-label">Journal Entries</div></div>
        </div>

        {/* Wellness Scores */}
        {w && w.overallScore > 0 && (
          <div className="profile-scores">
            <h3>🌿 Wellness Breakdown</h3>
            <div className="ps-bars">
              {[
                { label: '🏃 Physical', score: w.physicalScore, color: 'var(--green)' },
                { label: '🧠 Mental', score: w.mentalScore, color: 'var(--blue)' },
                { label: '💜 Emotional', score: w.emotionalScore, color: 'var(--lavender)' },
              ].map((b, i) => (
                <div className="ps-bar-item" key={i}>
                  <div className="ps-bar-top"><span>{b.label}</span><span style={{ color: b.color }}>{b.score}%</span></div>
                  <div className="ps-bar-track"><div className="ps-bar-fill" style={{ width: b.score + '%', background: b.color }} /></div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Export Report */}
        <div className="report-btn-wrap">
          <h3>📄 Export Wellness Report</h3>
          <p>Download a complete report of your wellness journey including scores, assessments, moods, and goals.</p>
          <button className="btn-primary" onClick={handleExportReport}>Download Report 📥</button>
        </div>

        {/* Edit Name */}
        <div className="profile-section">
          <h3>✏️ Edit Profile</h3>
          {nameSuccess && <div className="success-msg">{nameSuccess}</div>}
          <div className="profile-form-row full">
            <div className="form-group">
              <label>Full Name</label>
              <input className="form-input" type="text" value={editName} onChange={e => setEditName(e.target.value)} />
            </div>
          </div>
          <button className="btn-primary btn-sm" onClick={handleNameUpdate}>Save Changes</button>
        </div>

        {/* Change Password */}
        <div className="profile-section">
          <h3>🔒 Change Password</h3>
          {passSuccess && <div className="success-msg">{passSuccess}</div>}
          {passError && <div className="error-msg">{passError}</div>}
          <div className="profile-form-row full">
            <div className="form-group">
              <label>Current Password</label>
              <input className="form-input" type="password" value={passwords.currentPassword} onChange={e => setPasswords({ ...passwords, currentPassword: e.target.value })} />
            </div>
          </div>
          <div className="profile-form-row">
            <div className="form-group">
              <label>New Password</label>
              <input className="form-input" type="password" value={passwords.newPassword} onChange={e => setPasswords({ ...passwords, newPassword: e.target.value })} />
            </div>
            <div className="form-group">
              <label>Confirm New Password</label>
              <input className="form-input" type="password" value={passwords.confirmPassword} onChange={e => setPasswords({ ...passwords, confirmPassword: e.target.value })} />
            </div>
          </div>
          <button className="btn-primary btn-sm" onClick={handlePasswordChange}>Update Password</button>
        </div>
      </div>
    </div>
  );
}
